# Generated by Django 4.1 on 2023-10-02 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="performance",
        ),
    ]
