# Generated by Django 4.1 on 2023-09-27 20:55

from django.db import migrations, models
import theatre.models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to=theatre.models.actor_foto_file_path
            ),
        ),
    ]
