# Generated by Django 4.1 on 2023-09-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_actor_foto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="theatrehall",
            old_name="seats_in_rows",
            new_name="seats_in_row",
        ),
    ]
