# Generated by Django 4.1 on 2023-10-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_alter_ticket_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
