# Generated by Django 4.1 on 2023-09-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0004_rename_seats_in_rows_theatrehall_seats_in_row"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
