# Generated by Django 4.1 on 2023-10-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0005_alter_ticket_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
