# Generated by Django 4.1 on 2023-10-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0006_alter_reservation_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
    ]
