# Generated by Django 4.1 on 2023-10-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0007_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="row",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
