# Generated by Django 4.1 on 2023-10-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0008_alter_ticket_row_alter_ticket_seat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="row",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.PositiveIntegerField(),
        ),
    ]
