# Generated by Django 4.1 on 2023-10-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0009_alter_ticket_row_alter_ticket_seat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="play",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="theatrehall",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
