# Generated by Django 4.1 on 2023-10-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0011_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="average_rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
