# Generated by Django 4.1 on 2023-10-16 23:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("theatre", "0013_rating_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("play", "user")},
        ),
    ]
